# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
app = 'dev-next'
primary_region = 'ams'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
processes = ['app']

[deploy]
release_command = "yarn migrate:deploy"

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
