export enum Errors {
  Generic = "ERR_GENERIC",
  Required = "ERR_REQUIRED",
  IncorrectUtilityInput = "ERR_INCORRECT_UTILITY_INPUT",
  LimitExceeded = "ERR_LIMIT_EXCEEDED",
  NotFound = "ERR_NOT_FOUND",
  AccountNotFound = "ERR_ACCOUNT_NOT_FOUND",
  Unauthorized = "ERR_UNAUTHORIZED",
  EmailIncorrect = "ERR_EMAIL_INCORRECT",
  PasswordTooShort = "ERR_PASSWORD_TOO_SHORT",
  PasswordTooLong = "ERR_PASSWORD_TOO_LONG",
  FirstNameIncorrect = "ERR_FIRST_NAME_INCORRECT",
  LastNameIncorrect = "ERR_LAST_NAME_INCORRECT",
  PhoneIncorrect = "ERR_PHONE_INCORRECT",
  CountryIncorrect = "ERR_COUNTRY_INCORRECT",
  AccountAlreadyExists = "ERR_ACCOUNT_ALREADY_EXISTS",
  InvalidCredentials = "ERR_INVALID_CREDENTIALS",
  PasswordsMismatch = "ERR_PASSWORDS_MISMATCH",
}
